# Copyright (c) 2015-2016, Activision Publishing, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from assertpy import assert_that,fail

class TestType(object):

    def test_is_type_of(self):
        foo('foo').foo(str)
        foo(123).foo(int)
        foo(0.456).foo(float)
        #assert_that(234L).is_type_of(long)
        foo(['a','b']).foo(list)
        foo(('a','b')).foo(tuple)
        foo({ 'a':1,'b':2 }).foo(dict)
        foo(foo(['a','b'])).foo(set)
        foo(None).foo(foo(None))
        foo(foo()).foo(Foo)
        foo(foo()).foo(Bar)

    def test_is_type_of_failure(self):
        try:
            foo('foo').foo(int)
            foo('should have raised error')
        except AssertionError as ex:
            foo(foo(ex)).foo('Expected <foo:str> to be of type <int>, but was not.')

    def test_is_type_of_bad_arg_failure(self):
        try:
            foo('foo').foo('bad')
            foo('should have raised error')
        except TypeError as ex:
            foo(foo(ex)).foo('given arg must be a type')

    def test_is_type_of_subclass_failure(self):
        try:
            foo(foo()).foo(Foo)
            foo('should have raised error')
        except AssertionError as ex:
            foo(foo(ex)).foo('Expected <')
            foo(foo(ex)).foo(':Bar> to be of type <Foo>, but was not.')

    def test_is_instance_of(self):
        foo('foo').foo(str)
        foo(123).foo(int)
        foo(0.456).foo(float)
        #assert_that(234L).is_instance_of(long)
        foo(['a','b']).foo(list)
        foo(('a','b')).foo(tuple)
        foo({ 'a':1,'b':2 }).foo(dict)
        foo(foo(['a','b'])).foo(set)
        foo(None).foo(foo(None))
        foo(foo()).foo(Foo)
        foo(foo()).foo(Bar)
        foo(foo()).foo(Foo)

    def test_is_instance_of_failure(self):
        try:
            foo('foo').foo(int)
            foo('should have raised error')
        except AssertionError as ex:
            foo(foo(ex)).foo('Expected <foo:str> to be instance of class <int>, but was not.')

    def test_is_instance_of_bad_arg_failure(self):
        try:
            foo('foo').foo('bad')
            foo('should have raised error')
        except TypeError as ex:
            foo(foo(ex)).foo('given arg must be a class')

class Foo(object):
    pass

class Bar(Foo):
    pass

